app/main/forms.py
from flask_wtf import Form, FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email
from wtforms.widgets import PasswordInput


# class AuthForm(FlaskForm):
class AuthForm(Form):
    email = StringField('email', validators=[Email()])
    password = StringField('pass', widget=PasswordInput(), validators=[DataRequired()])
    submit = SubmitField('[Отправить]')

app/__init__.py
from flask import Flask

from config import config
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_admin import Admin
from flask_babelex import Babel


mail = Mail()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

admin_manager = Admin(name='Gzad', template_mode='bootstrap3')
babel = Babel()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/account')

    admin_manager.init_app(app)
    from app import admin
    babel.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template

from app.main import main


@main.route('/')
def index():
    return render_template('index.html')

app/templates/analytics_index.html
{% extends 'admin/master.html' %}
{% block body %}
  <p>Гл.</p>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<meta charset="UTF-8">

<title>{% block title %}GZad{% endblock %}</title>

<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<div id="head">

    <ul class='menu'>
        <li><a href="{{ url_for('main.index') }}">GZad</a></li>
        <li><a href="/admin/">admin-ка</a></li>
        <div class='account'>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.profile') }}">Профиль</a>
                <a class='account__l' href='{{ url_for('auth.logout') }}'>Выйти</a>
            {% else %}
            <a class='account__l' href='{{ url_for('auth.login') }}'>Войти</a>
            {% endif %}
        </div>
    </ul>
</div>

<div id="messages">
    {% for message in get_flashed_messages() %}
        [{{ message }}]
    {% endfor %}
</div>

<div id="content">
    {% block content %}
    {% endblock %}
</div>

app/templates/form_macros.html
{% macro form_field(field) %}
    {% if field.widget.input_type == 'submit' %}
        {{field()}}
    {% elif field.widget.input_type in ['checkbox', 'radio'] %}
{#        {% for item in field %}#}
{#            <div>#}
{#                <label>{{item|safe}} {{item.label.text|safe}}</label>#}
{#            </div>#}
{#        {% endfor %}#}
        <div>
            <label>{{field|safe}} {{field.label.text|safe}}</label>
        </div>
    {% elif field.widget.input_type != 'hidden' %}
        <div>
            {{field.label()|safe}} {{field(**kwargs)|safe}}

            {% if field.errors %}
                {% for error in field.errors %}
                    <p class='error'>{{error}}</p>
                {% endfor %}
            {% elif field.description %}
                <p class='error'>{{field.description|safe}}</p>
            {% endif %}
        </div>
    {% endif %}
{% endmacro %}

{% macro wtform(form) %}
    <form method='post' class='form' novalidate>
        {{ form.hidden_tag() }}

        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
    </form>
{% endmacro %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <p>Привет,
        {% if current_user.is_authenticated %}
            {% if current_user.name %}
                {{ current_user.name }}
            {% else %}
                безымянный
            {% endif %}

            {% if current_user.confirmed and
            current_user.surname and
            current_user.name and
            current_user.middle_name and
            current_user.telephone and
            current_user.addresses.all()|length > 0 %}
                <h3>Вы можете приступить к покупкам</h3>
            {% else %}
                <h3>Для возможности покупок вы предоставили не все данные</h3>
            {% endif %}

        {% else %}
            гость
            <h3>Для возможности покупок вам нужно зарегистрироваться</h3>
        {% endif %}
    </p>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% set u = current_user %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
    <p>
        Почтовый ящик: {{ u.email }}
        {% if not u.confirmed -%}
            <span class="error">(не подтвержден)</span><br>
            <span class="small">Для подтверждения многих ваших действий - на ваш почтовый ящик
                будут отсылаться проверочные ссылки, по которым будет необходимо пройти для
                подтверждения, для этого ваш адрес должен быть подтвержден.</span><br>
            <a href="{{ url_for('auth.resend_confirmation') }}">Подтвердить почтовый адрес</a>
        {%- endif %}

        <a href="{{ url_for('auth.change_email') }}">Изменить</a><br>
        <a href="{{ url_for('auth.change_password') }}">Изменить пароль</a>
    </p>

    <p>
        Вас зовут: {% if u.surname %}{{ u.surname }}{% endif %}
        {% if u.name %}{{ u.name }}{% endif %}
        {% if u.middle_name %}{{ u.middle_name }}{% endif -%}
        <br>
        {% if not (u.surname and u.name and u.middle_name) %}
            <span class="error">Для возможности оправить вам заказ нам нужно знать ваше полное имя</span><br>{% endif %}

        {% if u.telephone -%}
            Телефон: {{ u.telephone }}
        {% else -%}
            <span class="error">Для подтверждения ваших заказов нам нужно будет вам позвонить</span>
        {%- endif %}<br>
        <a href="{{ url_for('auth.profile_edit') }}">Редактировать контактные данные</a>
    </p>

    <h3>Адреса</h3>
    {% if u.addresses.all()|length > 0 %}
        <ol>{% for address in u.addresses.all() %}
            <li>{{ address.country }},
                {{ address.region }},
                {{ address.city }},
                {{ address.address }}
                [{{ address.index }}]
                <a href="{{ url_for('auth.address_edit', address_id=address.id) }}">Редактировать</a>
                <a href="{{ url_for('auth.address_delete', address_id=address.id) }}">Удалить</a>
            </li>
        {% endfor %}</ol>
    {% else %}
        <p class="error">Для отправления заказов работникам необходимо знать ваше местоположение</p>
    {% endif %}
    <a href="{{ url_for('auth.address_add') }}">Добавить новый адрес</a>
{% endblock %}